services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=romeo
      - POSTGRES_USER=romeo
      - POSTGRES_PASSWORD=romeo_password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U romeo -d romeo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
